type LayerType =
  | "ADBE Vector Layer"
  | "ADBE Text Layer"
  | "ADBE Camera Layer"
  | "ADBE Light Layer"
  | "Null"
  | "Adjustment"
  | "Guide"
  | "Precomp"
  | "Solid"
  | "Placeholder"
  | "Missing Footage"
  | "Data"
  | "Audio"
  | "Image"
  | "Invalid";
