export const menuOverview = JSON.stringify({
  templates: [
    {
      name: "Boogle Pie",
      id: 14,
      comp: "Boogle Pie",
      folder: "Boogle Pie",
      fields: [
        {
          type: "Text",
          options: [],
          title: "This is another text Item",
          tag: "",
          tab: "",
          value: "This is another text Item",
        },
        {
          type: "Text",
          options: [],
          title: "A Whole Wheel of Fish",
          tag: "",
          tab: "",
          value: "A Whole Wheel of Fish",
        },
        {
          type: "Text",
          options: ["visible"],
          title: "Subtext",
          tag: "",
          tab: "Overview",
          value: "Subtext",
        },
        {
          type: "Media",
          options: ["background-size"],
          title: "Background",
          tag: "",
          tab: "Overview",
          value: "DarkGrey",
        },
        {
          type: "Color",
          options: ["background-size"],
          title: "Hue",
          tag: "",
          tab: "Overview",
          value: "1,0,0,1",
        },
      ],
    },
    {
      name: "Erything",
      id: 120,
      comp: "Erything",
      folder: "Erything",
      fields: [
        { type: "Group", options: [], title: "", tag: "", tab: "Options" },
        { type: "Group", options: [], title: "", tag: "", tab: "Overview" },
        {
          type: "Font",
          options: [],
          title: "Heading",
          tag: "",
          tab: "Options",
          value: "Montserrat-Black",
        },
        {
          type: "Text",
          options: [],
          title: "A Part Wheel of Fish",
          tag: "Heading",
          tab: "Overview",
          value: "A Whole Wheel of Fish",
        },
        {
          type: "Text",
          options: ["visible"],
          title: "Subtext 1",
          tag: "",
          tab: "Overview",
          value: "Subtext",
        },
        {
          type: "Media",
          options: [],
          title: "Weird Vid",
          tag: "",
          tab: "Overview",
          value: "Pale Gray-Blue Solid 1",
        },
        {
          type: "Text",
          options: [],
          title: "A Whole Wheel of Fish",
          tag: "",
          tab: "Overview",
          value: "A Whole Wheel of Fish",
        },
        {
          type: "Text",
          options: ["visible"],
          title: "Subtext 2",
          tag: "",
          tab: "Overview",
          value: "Subtext",
        },
        {
          type: "Media",
          options: ["background-size"],
          title: "Second Background",
          tag: "",
          tab: "Overview",
          value: "DarkGrey",
        },
        {
          type: "Media",
          options: [],
          title: "First Background",
          tag: "",
          tab: "Overview",
          value: "DarkGrey",
        },
        {
          type: "Color",
          options: [],
          title: "Text Color",
          tag: "",
          tab: "Options",
          value: "0.27780556678772,0.21357502043247,0.64104169607162,1",
        },
        {
          type: "Color",
          options: [],
          title: "Second Color",
          tag: "",
          tab: "Options",
          value: "0.64104169607162,0.35373559594154,0.21357502043247,1",
        },
      ],
    },
    {
      name: "Font Guide",
      id: 187,
      comp: "Font Guide",
      folder: "Font Guide",
      fields: [
        {
          type: "Font",
          options: [],
          title: "Thin",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Thin",
        },
        {
          type: "Font",
          options: [],
          title: "ExtraLight",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-ExtraLight",
        },
        {
          type: "Font",
          options: [],
          title: "Light",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Light",
        },
        {
          type: "Font",
          options: [],
          title: "Regular",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Regular",
        },
        {
          type: "Font",
          options: [],
          title: "Medium",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Medium",
        },
        {
          type: "Font",
          options: [],
          title: "SemiBold",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-SemiBold",
        },
        {
          type: "Font",
          options: [],
          title: "Bold",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Bold",
        },
        {
          type: "Font",
          options: [],
          title: "Black",
          tag: "",
          tab: "Montserrat",
          value: "Montserrat-Black",
        },
      ],
    },
  ],
  fonts: [
    { font: "Montserrat-SemiBold", fontFamily: "Montserrat", fontStyle: "SemiBold" },
    { font: "Montserrat-Black", fontFamily: "Montserrat", fontStyle: "Black" },
    { font: "Montserrat-Thin", fontFamily: "Montserrat", fontStyle: "Thin" },
    { font: "Montserrat-ExtraLight", fontFamily: "Montserrat", fontStyle: "ExtraLight" },
    { font: "Montserrat-Light", fontFamily: "Montserrat", fontStyle: "Light" },
    { font: "Montserrat-Regular", fontFamily: "Montserrat", fontStyle: "Regular" },
    { font: "Montserrat-Medium", fontFamily: "Montserrat", fontStyle: "Medium" },
    { font: "Montserrat-Bold", fontFamily: "Montserrat", fontStyle: "Bold" },
  ],
  libraryAssets: [
    {
      name: "beach2.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/beach2.jpg",
      fileName: "beach2.jpg",
      libraryPath: "/beach2.jpg",
      typeName: "Footage",
    },
    {
      name: "DarkGrey",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/DarkGrey",
      typeName: "Footage",
    },
    {
      name: "Null 1",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 1",
      typeName: "Footage",
    },
    {
      name: "Null 2",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 2",
      typeName: "Footage",
    },
    {
      name: "Null 3",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 3",
      typeName: "Footage",
    },
    {
      name: "Null 4",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 4",
      typeName: "Footage",
    },
    {
      name: "Null 5",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 5",
      typeName: "Footage",
    },
    {
      name: "Null 6",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 6",
      typeName: "Footage",
    },
    {
      name: "Null 7",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 7",
      typeName: "Footage",
    },
    {
      name: "Null 8",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 8",
      typeName: "Footage",
    },
    {
      name: "Null 9",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 9",
      typeName: "Footage",
    },
    {
      name: "Null 10",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 10",
      typeName: "Footage",
    },
    {
      name: "Null 11",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 11",
      typeName: "Footage",
    },
    {
      name: "Null 12",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 12",
      typeName: "Footage",
    },
    {
      name: "Null 13",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 13",
      typeName: "Footage",
    },
    {
      name: "Null 14",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 14",
      typeName: "Footage",
    },
    {
      name: "Null 15",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 15",
      typeName: "Footage",
    },
    {
      name: "Null 16",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 16",
      typeName: "Footage",
    },
    {
      name: "Null 17",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 17",
      typeName: "Footage",
    },
    {
      name: "Null 18",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 18",
      typeName: "Footage",
    },
    {
      name: "Null 19",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 19",
      typeName: "Footage",
    },
    {
      name: "Null 20",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 20",
      typeName: "Footage",
    },
    {
      name: "Null 21",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 21",
      typeName: "Footage",
    },
    {
      name: "Null 22",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 22",
      typeName: "Footage",
    },
    {
      name: "Null 23",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 23",
      typeName: "Footage",
    },
    {
      name: "Null 24",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 24",
      typeName: "Footage",
    },
    {
      name: "Null 25",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 25",
      typeName: "Footage",
    },
    {
      name: "Null 26",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 26",
      typeName: "Footage",
    },
    {
      name: "Null 27",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 27",
      typeName: "Footage",
    },
    {
      name: "Null 28",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 28",
      typeName: "Footage",
    },
    {
      name: "Null 29",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 29",
      typeName: "Footage",
    },
    {
      name: "Null 30",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 30",
      typeName: "Footage",
    },
    {
      name: "Null 31",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 31",
      typeName: "Footage",
    },
    {
      name: "Null 32",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 32",
      typeName: "Footage",
    },
    {
      name: "Null 33",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 33",
      typeName: "Footage",
    },
    {
      name: "Null 34",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 34",
      typeName: "Footage",
    },
    {
      name: "Null 35",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 35",
      typeName: "Footage",
    },
    {
      name: "Null 36",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 36",
      typeName: "Footage",
    },
    {
      name: "Null 37",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 37",
      typeName: "Footage",
    },
    {
      name: "Null 38",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 38",
      typeName: "Footage",
    },
    {
      name: "Null 39",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 39",
      typeName: "Footage",
    },
    {
      name: "Null 40",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 40",
      typeName: "Footage",
    },
    {
      name: "Null 41",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 41",
      typeName: "Footage",
    },
    {
      name: "Null 42",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 42",
      typeName: "Footage",
    },
    {
      name: "Null 43",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 43",
      typeName: "Footage",
    },
    {
      name: "Null 44",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 44",
      typeName: "Footage",
    },
    {
      name: "Null 45",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 45",
      typeName: "Footage",
    },
    {
      name: "Null 46",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 46",
      typeName: "Footage",
    },
    {
      name: "Null 47",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 47",
      typeName: "Footage",
    },
    {
      name: "Null 48",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 48",
      typeName: "Footage",
    },
    {
      name: "Null 49",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Null 49",
      typeName: "Footage",
    },
    {
      name: "Pale Gray-Blue Solid 1",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Solids/Pale Gray-Blue Solid 1",
      typeName: "Footage",
    },
    {
      name: "Boogle Pie",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Templates/Boogle Pie/Boogle Pie",
      typeName: "Composition",
    },
    {
      name: "Erything",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Templates/Erything/Erything",
      typeName: "Composition",
    },
    {
      name: "Slide1",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Templates/Erything/Precomps/Slide1",
      typeName: "Composition",
    },
    {
      name: "Slide2",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Templates/Erything/Precomps/Slide2",
      typeName: "Composition",
    },
    {
      name: "Font Guide",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/Templates/Font Guide/Font Guide",
      typeName: "Composition",
    },
    {
      name: "beach1.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/beach1.jpg",
      fileName: "beach1.jpg",
      libraryPath: "/TOOLBOX/Links/beach1.jpg",
      typeName: "Footage",
    },
    {
      name: "buttercups.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/buttercups.jpg",
      fileName: "buttercups.jpg",
      libraryPath: "/TOOLBOX/Links/buttercups.jpg",
      typeName: "Footage",
    },
    {
      name: "mountain1.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/mountain1.jpg",
      fileName: "mountain1.jpg",
      libraryPath: "/TOOLBOX/Links/mountain1.jpg",
      typeName: "Footage",
    },
    {
      name: "mountain2.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/mountain2.jpg",
      fileName: "mountain2.jpg",
      libraryPath: "/TOOLBOX/Links/mountain2.jpg",
      typeName: "Footage",
    },
    {
      name: "mountain3.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/mountain3.jpg",
      fileName: "mountain3.jpg",
      libraryPath: "/TOOLBOX/Links/mountain3.jpg",
      typeName: "Footage",
    },
    {
      name: "mountain4.jpg",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/mountain4.jpg",
      fileName: "mountain4.jpg",
      libraryPath: "/TOOLBOX/Links/mountain4.jpg",
      typeName: "Footage",
    },
    {
      name: "Music_Birds.m4a",
      hasVideo: false,
      hasAudio: true,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/Music_Birds.m4a",
      fileName: "Music_Birds.m4a",
      libraryPath: "/TOOLBOX/Links/Music_Birds.m4a",
      typeName: "Footage",
    },
    {
      name: "Music_Easter.m4a",
      hasVideo: false,
      hasAudio: true,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/Music_Easter.m4a",
      fileName: "Music_Easter.m4a",
      libraryPath: "/TOOLBOX/Links/Music_Easter.m4a",
      typeName: "Footage",
    },
    {
      name: "peace_on_earth.png",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/peace_on_earth.png",
      fileName: "peace_on_earth.png",
      libraryPath: "/TOOLBOX/Links/peace_on_earth.png",
      typeName: "Footage",
    },
    {
      name: "poodle.png",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/poodle.png",
      fileName: "poodle.png",
      libraryPath: "/TOOLBOX/Links/poodle.png",
      typeName: "Footage",
    },
    {
      name: "stars.png",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/stars.png",
      fileName: "stars.png",
      libraryPath: "/TOOLBOX/Links/stars.png",
      typeName: "Footage",
    },
    {
      name: "tree1.png",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/tree1.png",
      fileName: "tree1.png",
      libraryPath: "/TOOLBOX/Links/tree1.png",
      typeName: "Footage",
    },
    {
      name: "tree2.png",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      file: "~/Creative%20Cloud%20Files/Script%20Testing/Links/tree2.png",
      fileName: "tree2.png",
      libraryPath: "/TOOLBOX/Links/tree2.png",
      typeName: "Footage",
    },
    {
      name: "Boogle Pie",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/User\\/Comps/Boogle 2000/Boogle Pie",
      typeName: "Composition",
    },
    {
      name: "Erything",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/User\\/Comps/Erything 3000/Erything",
      typeName: "Composition",
    },
    {
      name: "Slide1",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/User\\/Comps/Erything 3000/Precomps/Slide1",
      typeName: "Composition",
    },
    {
      name: "Slide2",
      hasVideo: true,
      hasAudio: false,
      brokenLink: false,
      libraryPath: "/User\\/Comps/Erything 3000/Precomps/Slide2",
      typeName: "Composition",
    },
  ],
} as SorcererOverview);
